import Footer from "@/components/Footer";
import Header from "@/components/Header";
import type { Metadata } from "next";
import "@/styles";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <Header />
        <main className="flex justify-center p-4">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
